"""Offline AI datasets, model packs, and local/pretrained inference runtimes."""

from batikcraft_studio.ai.batikbrew_generation import (
    SDXL_BASE_MODEL_ID,
    BatikBrewAnalysis,
    BatikBrewGenerationOptions,
    BatikBrewSDXLGenerationProvider,
    analyse_inspiration,
    create_tile_preview,
    make_tileable,
    with_plan_context,
)
from batikcraft_studio.ai.dataset_pack import (
    BATIK_DATASET_EXTENSION,
    BATIK_DATASET_FORMAT,
    BATIK_DATASET_SCHEMA_VERSION,
    BatikDatasetBundle,
    BatikDatasetError,
    BatikDatasetMetadata,
    BatikTrainingSample,
    build_batik_dataset,
    load_batik_dataset,
)
from batikcraft_studio.ai.global_runtime import (
    GlobalPretrainedBatikBackgroundProvider,
    GlobalPretrainedImg2ImgBatificationProvider,
    apply_global_runtime_to_background_options,
    configure_pipeline_memory_features,
    pretrained_batification_options_from_global,
)
from batikcraft_studio.ai.model_pack import (
    BATIK_MODEL_EXTENSION,
    BATIK_MODEL_FORMAT,
    BATIK_MODEL_SCHEMA_VERSION,
    BatikModelError,
    BatikModelManifest,
    InstalledBatikModel,
    OfflineModelLibrary,
    build_batik_model_pack,
    default_model_library_root,
    discover_bundled_model_packs,
)
from batikcraft_studio.ai.offline_runtime import (
    OfflineLoraBatificationProvider,
    OfflineRuntimeConfig,
)
from batikcraft_studio.ai.pretrained_background import (
    AIBatikBackgroundOptions,
    AIBatikBackgroundResult,
    PretrainedBatikBackgroundProvider,
)
from batikcraft_studio.ai.pretrained_batification import (
    PretrainedAIBatificationOptions,
    PretrainedAIBatificationResult,
    PretrainedImg2ImgBatificationProvider,
)
from batikcraft_studio.ai.runtime_settings import (
    AI_SETTINGS_SCHEMA_VERSION,
    DEFAULT_MODEL_ID,
    AIRuntimeRecommendation,
    AIRuntimeReport,
    AIRuntimeSettings,
    AIRuntimeSettingsStore,
    default_ai_cache_dir,
    default_ai_settings_path,
    diagnose_ai_runtime,
    get_ai_runtime_store,
    load_ai_runtime_settings,
    save_ai_runtime_settings,
)

__all__ = [
    "AI_SETTINGS_SCHEMA_VERSION",
    "BATIK_DATASET_EXTENSION",
    "BATIK_DATASET_FORMAT",
    "BATIK_DATASET_SCHEMA_VERSION",
    "BATIK_MODEL_EXTENSION",
    "BATIK_MODEL_FORMAT",
    "BATIK_MODEL_SCHEMA_VERSION",
    "DEFAULT_MODEL_ID",
    "SDXL_BASE_MODEL_ID",
    "AIBatikBackgroundOptions",
    "AIBatikBackgroundResult",
    "AIRuntimeRecommendation",
    "AIRuntimeReport",
    "AIRuntimeSettings",
    "AIRuntimeSettingsStore",
    "BatikBrewAnalysis",
    "BatikBrewGenerationOptions",
    "BatikBrewSDXLGenerationProvider",
    "BatikDatasetBundle",
    "BatikDatasetError",
    "BatikDatasetMetadata",
    "BatikModelError",
    "BatikModelManifest",
    "BatikTrainingSample",
    "GlobalPretrainedBatikBackgroundProvider",
    "GlobalPretrainedImg2ImgBatificationProvider",
    "InstalledBatikModel",
    "OfflineLoraBatificationProvider",
    "OfflineModelLibrary",
    "OfflineRuntimeConfig",
    "PretrainedAIBatificationOptions",
    "PretrainedAIBatificationResult",
    "PretrainedBatikBackgroundProvider",
    "PretrainedImg2ImgBatificationProvider",
    "analyse_inspiration",
    "apply_global_runtime_to_background_options",
    "build_batik_dataset",
    "build_batik_model_pack",
    "configure_pipeline_memory_features",
    "create_tile_preview",
    "default_ai_cache_dir",
    "default_ai_settings_path",
    "default_model_library_root",
    "diagnose_ai_runtime",
    "discover_bundled_model_packs",
    "get_ai_runtime_store",
    "load_ai_runtime_settings",
    "load_batik_dataset",
    "make_tileable",
    "pretrained_batification_options_from_global",
    "save_ai_runtime_settings",
    "with_plan_context",
]
